# Generated by Django 4.1.2 on 2022-11-09 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("outfits", "0003_alter_product_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="parent",
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="outfits.category"
            ),
        ),
        migrations.DeleteModel(
            name="Type",
        ),
    ]
