# Generated by Django 4.1.2 on 2022-11-10 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outfits', '0004_remove_category_parent_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='weather_value',
            field=models.IntegerField(),
        ),
    ]
