# Generated by Django 4.1.2 on 2022-11-10 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outfits', '0006_suggestion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Suggestion',
        ),
    ]
