# Generated by Django 4.1.2 on 2022-11-10 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outfits', '0007_delete_suggestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='model',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='shade',
            field=models.CharField(max_length=20),
        ),
    ]
