# Generated by Django 4.1.2 on 2022-11-17 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("outfits", "0010_weather_suggestion_weather"),
    ]

    operations = [
        migrations.AddField(
            model_name="weather",
            name="rain",
            field=models.FloatField(null=True),
        ),
    ]
