# Generated by Django 4.1.2 on 2023-03-15 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="latitude",
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="longitude",
            field=models.CharField(max_length=15),
        ),
    ]
